Apply new style/新しいスタイルの適用
jsnog/jsnog.github.io pull request #1
Opened 2023-06-07 14:03 UTC by palz01pa

## Done title align to center/タイトルの位置を中央に
title arign changed left to center.
タイトルの位置を中央に変更しました。

## Add Twitter widget copyright/Twitterのウィジェットを追加
Added Twitter widget to right side and copyright to footer.
Twitterのウィジェットを右側に追加しました。

## Changed style/ スタイルの変更
Display changed to flex and divided into three left,
center and right and made Twitter widget hover.
ディスプレイをflexに変更し左・中央・右の三つに分割し、
Twitterウィジェットを追従するようにしました。

## Note/注意
Translated Japanese into English with Google Translate.
Google翻訳で日本語を英語に翻訳しました。

2023-06-08 11:26 UTC, masebb requested changes
PRありがとうございます！！！！

申し訳ないのですが、いくつか修正して頂きたいところがあるので、ご確認の上修正もしくはコメントでの反論をお願いします～

2023-06-08 11:26 UTC, masebb commented on index.html
> +    <address>Copyright(C)2023 JSNOG,Allright Reserved.</address>
Copyrightの表示は不要かな～と思う
(JSNOGが権利を有するにしても、JSNOGの誰が権利を有するのか不明瞭+OSS(Githubで公開)のため)

2023-06-08 11:26 UTC, masebb commented on index.html
> +  <link rel="stylesheet" type="text/css" href="/Style/style.css">
href=Style/style.cssにしないと絶対パスになってしまい当方環境(FireFox最新)では動きませんでしたので、修正をお願いします

2023-06-08 11:26 UTC, masebb commented on closed-bgp-asobi.html
> +    <address>Copyright(C)2023 JSNOG,Allright Reserved.</address>
こちらのCopyright表示も削除をお願いします～

2023-06-08 11:26 UTC, masebb commented on closed-bgp-asobi.html
> +  <link rel="stylesheet" type="text/css" href="/Style/style.css">
こちらも同様にお願いします

2023-06-08 11:47 UTC, palz01pa commented on index.html
> +  <link rel="stylesheet" type="text/css" href="/Style/style.css">
今後のページの追加の可能性を考慮して、
ルートディレクトリ配下である "/Style" に配置しています。

他のディレクトリ配下に配置している場合は、
ルートディレクトリに配置してください。

2023-06-08 12:03 UTC, palz01pa commented on index.html
> +    <address>Copyright(C)2023 JSNOG,Allright Reserved.</address>
権利については全員が作成・編集権を有すると考え、
画像等を除き、誰という個人ではなく、
"JSNOG" というグループで有すると考えています。

不要であれば、再度ご返信ください。
また、別に表示したい文字列がありましたら、
そちらもご返信にご記入ください。

2023-06-10 03:19 UTC, palz01pa commented
Copyright を削除し、
お願いを footer に記載するよう変更しました。

2023-06-10 10:35 UTC, masebb commented
返信遅れて申し訳ないです
Copyrightの件ありがとうございます。まとめて書かずして本当に申し訳ないのですが、最後にfooterのスタイルについてコメント書きましたので、ご確認いただきたいです。

上記の件が終わり次第Mergeしたいと思っておりますので、よろしくお願いいたします～

2023-06-11 03:32 UTC, palz01pa commented
修正点とはどこでしょうか...

2023-06-11 09:10 UTC, masebb commented
前と同じのコードレビューの所で書いてます～
https://github.com/jsnog/jsnog.github.io/pull/1/files で確認できるかと思います

2023-06-11 11:13 UTC, palz01pa commented
確認できません...

2023-06-11 14:38 UTC, masebb reviewed
ごめんなさい！Pendingのまんまでした...

2023-06-11 14:38 UTC, masebb commented on closed-bgp-asobi.html
> +  <link rel="stylesheet" type="text/css" href="/Style/style.css">
たしかに不要でした
お手数おかけしまして申し訳ない

2023-06-11 14:38 UTC, masebb commented on Style/style.css
> +    letter-spacing: 5px;
このletter-spacingはよくわからないので削除して頂きたいです～

2023-06-11 14:38 UTC, masebb commented on Style/style.css
> +    background-color: #313131;
スタイル統一のため、background-colorはない方が良いかも

2023-06-11 14:38 UTC, masebb commented on Style/style.css
> +    color: #FFFFFF;
background-colorを無くす場合は消す(黒にする)

2023-06-12 09:47 UTC, palz01pa commented
>このletter-spacingはよくわからないので削除して頂きたいです～

letter-spacing は文字の間隔を調整するためのものです

その他については修正いたします
>スタイル統一のため、background-colorはない方が良いかも

>background-colorを無くす場合は消す(黒にする)

letter-spacing あり
![pic000](https://github.com/jsnog/jsnog.github.io/assets/82742736/3ab7aa43-f1b8-40e8-b80a-4c6c5c90d677)
letter-spacing なし
![pic001](https://github.com/jsnog/jsnog.github.io/assets/82742736/abca1bb3-3dc0-48f4-ae8a-bb48ec9a85c8)

2023-06-12 10:49 UTC, masebb commented
修正ありがとうございました！
letter-spacingについてなのですが、どうしてわざわざFooterの各文字に空白を付けるのかが不明瞭なのですが、これといった理由がなければ、スタイル統一のため削除して頂ければと思いますが、どうでしょうか?

ほんと色々文句付けて申し訳ないです

2023-06-12 10:52 UTC, palz01pa commented
letter-spacingについて、
一言でまとめると見た目です...()
※個人的な意見です

2023-06-13 13:21 UTC, masebb commented
これはこれでありな気もしてきたのでこのままMergeいたします!
PR及び私のコメントに付き合ってくださってありがとうございました！

2023-06-13 13:21 UTC, merged